## @file
# Azure Pipeline build file for Slim Bootloader
#
# Copyright (c) 2020, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

trigger:
- master

pr:
- master


jobs:


- job: UPLD_QEMU

  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.x'
      architecture: 'x64'
    displayName: Set Python version

  - bash: |
      git config --global user.email "you@example.com"
      git config --global user.name  "Your Name"
      sudo apt-get update
    displayName: Update apt

  - bash: |
      sudo apt-get install -y nasm uuid-dev iasl qemu-system-x86
    displayName: Install required tools

  - script: |
      python upld_test.py
    displayName: 'Run QEMU tests'
